"""billing: credit ledger

Revision ID: 3fa508f4ae76
Revises: f3b30195d51a
Create Date: 2026-06-25 04:16:08.133825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa508f4ae76'
down_revision: Union[str, Sequence[str], None] = 'f3b30195d51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_ledger_idempotency_key')
    )
    with op.batch_alter_table('credit_ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_ledger_entries_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_entries_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_ledger_workspace_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('workspace_credits',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('balance_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_credits')
    with op.batch_alter_table('credit_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_workspace_created')
        batch_op.drop_index(batch_op.f('ix_credit_ledger_entries_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_entries_run_id'))

    op.drop_table('credit_ledger_entries')
    # ### end Alembic commands ###
