"""pg tenancy: shared leads/signals tables + RLS

Revision ID: c42d0273d9bd
Revises: f7274d0aacd9
Create Date: 2026-06-25 10:53:59.322460

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42d0273d9bd'
down_revision: Union[str, Sequence[str], None] = 'f7274d0aacd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Name of the non-superuser, non-BYPASSRLS application role that RLS policies
# are written for and that the runtime connects as in production. Overridable so
# a deployment can use its own role name; the default matches the docs/runbook.
# This must match apps.api.core.config.settings.APP_DB_ROLE.
APP_DB_ROLE = os.getenv("YUPCHA_APP_DB_ROLE", "yupcha_app")

# Columns that feed the full-text search vector (PG analogue of the SQLite
# FTS5 table over the same columns in services/leadgen/db.py).
_FTS_COLUMNS = ("company", "city", "specialization", "notes", "description")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_confidence', sa.String(), nullable=True),
    sa.Column('email_provider', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_provider', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_title', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('employee_count_exact', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('revenue_range', sa.String(), nullable=True),
    sa.Column('founded_year', sa.String(), nullable=True),
    sa.Column('founding_year', sa.String(), nullable=True),
    sa.Column('industry_tags', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('funding_stage', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('secondary_emails', sa.Text(), nullable=True),
    sa.Column('secondary_phones', sa.Text(), nullable=True),
    sa.Column('decision_makers', sa.Text(), nullable=True),
    sa.Column('glassdoor_rating', sa.String(), nullable=True),
    sa.Column('hiring_signals', sa.Text(), nullable=True),
    sa.Column('enrichment_attempts', sa.Integer(), nullable=True),
    sa.Column('enrichment_waterfall', sa.Text(), nullable=True),
    sa.Column('last_funding_amount', sa.String(), nullable=True),
    sa.Column('investors', sa.Text(), nullable=True),
    sa.Column('recent_news', sa.Text(), nullable=True),
    sa.Column('google_rating', sa.String(), nullable=True),
    sa.Column('revenue_estimate', sa.String(), nullable=True),
    sa.Column('email_verify', sa.String(), nullable=True),
    sa.Column('email_presence', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('yupcha_value_prop', sa.Text(), nullable=True),
    sa.Column('company_need', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('last_enriched_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'company', 'city', name='uq_leads_ws_company_city')
    )
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_index('ix_leads_ws_score', 'leads', ['workspace_id', 'score'], unique=False)
    op.create_index('ix_leads_ws_source', 'leads', ['workspace_id', 'source'], unique=False)
    op.create_index('ix_leads_ws_status', 'leads', ['workspace_id', 'status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_workspace_id'), 'signals', ['workspace_id'], unique=False)
    op.create_index('ix_signals_ws_created', 'signals', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_signals_ws_lead', 'signals', ['workspace_id', 'lead_id'], unique=False)
    op.create_index('ix_signals_ws_type', 'signals', ['workspace_id', 'signal_type'], unique=False)
    # ### end Alembic commands ###

    # ── Postgres-only: tsvector full-text search + Row-Level Security ──
    # Autogenerate cannot emit any of this; it is hand-authored and guarded on
    # the dialect so the SQLite/self-host create path is untouched.
    if op.get_bind().dialect.name == "postgresql":
        _pg_upgrade()


def _pg_upgrade() -> None:
    """Postgres-only DDL: tsvector/GIN search + RLS enable/force/policies +
    the application role and its grants."""
    # 1) Full-text search: a generated-by-trigger tsvector column + GIN index.
    #    (PG replacement for the SQLite FTS5 virtual table + sync triggers.)
    op.execute("ALTER TABLE leads ADD COLUMN search_tsv tsvector")
    _tsv_expr = " || ' ' || ".join(
        f"coalesce(NEW.{c}, '')" for c in _FTS_COLUMNS
    )
    op.execute(
        f"""
        CREATE OR REPLACE FUNCTION leads_search_tsv_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_tsv := to_tsvector('english', {_tsv_expr});
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER leads_search_tsv_update
        BEFORE INSERT OR UPDATE ON leads
        FOR EACH ROW EXECUTE FUNCTION leads_search_tsv_trigger()
        """
    )
    op.execute("CREATE INDEX ix_leads_search_tsv ON leads USING gin (search_tsv)")

    # 2) The application role. Created NOLOGIN (a group role): production grants
    #    it to the concrete login role(s); tests CREATE a login role and GRANT
    #    this role to it. Crucially it is NOT superuser and NOT BYPASSRLS, so the
    #    policies below actually bind. Idempotent (skips if it already exists).
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_DB_ROLE}') THEN
                CREATE ROLE {APP_DB_ROLE} NOLOGIN NOSUPERUSER NOBYPASSRLS;
            END IF;
        END
        $$
        """
    )
    # Least-privilege DML grants (no DDL). Alembic/db_init run as the table
    # OWNER, not this role, so schema changes are unaffected.
    for tbl in ("leads", "signals"):
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {tbl} TO {APP_DB_ROLE}")
    # The leads PK is a SERIAL/identity — the app role needs the sequence to insert.
    op.execute(
        f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {APP_DB_ROLE}"
    )

    # 3) Row-Level Security. ENABLE makes the policy apply to ordinary roles;
    #    FORCE makes it apply to the TABLE OWNER too (so even the migration/owner
    #    connection is scoped — important for the bulk-load path). The policy
    #    reads app.workspace_id; current_setting(..., true) returns NULL when the
    #    GUC is unset, and `workspace_id = NULL` is never true → fail closed
    #    (zero rows), never a leak. WITH CHECK blocks cross-tenant writes.
    for tbl in ("leads", "signals"):
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {tbl} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {tbl}_workspace_isolation ON {tbl}
            USING (workspace_id = current_setting('app.workspace_id', true))
            WITH CHECK (workspace_id = current_setting('app.workspace_id', true))
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        _pg_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_ws_type', table_name='signals')
    op.drop_index('ix_signals_ws_lead', table_name='signals')
    op.drop_index('ix_signals_ws_created', table_name='signals')
    op.drop_index(op.f('ix_signals_workspace_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_leads_ws_status', table_name='leads')
    op.drop_index('ix_leads_ws_source', table_name='leads')
    op.drop_index('ix_leads_ws_score', table_name='leads')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###


def _pg_downgrade() -> None:
    """Tear down the Postgres-only objects before the tables are dropped.

    The app role is intentionally NOT dropped: it may be shared/owned outside
    this migration and may still be granted to login roles. Revoking its grants
    is implicit once the tables disappear.
    """
    for tbl in ("leads", "signals"):
        op.execute(f"DROP POLICY IF EXISTS {tbl}_workspace_isolation ON {tbl}")
    op.execute("DROP TRIGGER IF EXISTS leads_search_tsv_update ON leads")
    op.execute("DROP FUNCTION IF EXISTS leads_search_tsv_trigger()")
    op.execute("DROP INDEX IF EXISTS ix_leads_search_tsv")
