"""baseline schema

Revision ID: db9a4b81b1e6
Revises: 
Create Date: 2026-06-25 03:50:56.008585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9a4b81b1e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workbook_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(), nullable=False),
    sa.Column('goal', sa.String(length=512), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('total_cost_usd', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workbook_id', 'lead_id', 'column_id', name='uq_cell_trace')
    )
    with op.batch_alter_table('cell_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cell_traces_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cell_traces_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('company_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=64), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_city', sa.String(length=128), nullable=True),
    sa.Column('identity_keys', sa.JSON(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('source_agreement', sa.JSON(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_entities_corroboration_count'), ['corroboration_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_entities_primary_domain'), ['primary_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_entities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('email_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('source_link_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_data_id'), ['id'], unique=False)

    op.create_table('entity_merge_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kept_id', sa.String(), nullable=True),
    sa.Column('merged_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('reverted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_merge_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_merge_log_kept_id'), ['kept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_merge_log_merged_id'), ['merged_id'], unique=False)

    op.create_table('entity_review_pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('candidate', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_review_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_review_pairs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_review_pairs_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_type'), ['type'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_url'), ['url'], unique=True)

    op.create_table('person_intel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('articles', sa.JSON(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('companies', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('raw_sources', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_intel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_intel_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_intel_linkedin_url'), ['linkedin_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_intel_username'), ['username'], unique=False)

    op.create_table('provider_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('total_confidence', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'field', name='uq_provider_field')
    )
    with op.batch_alter_table('provider_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_stats_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_stats_provider'), ['provider'], unique=False)

    op.create_table('scrape_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_history_url'), ['url'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('workbook_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workbook_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbook_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbook_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbook_activity_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('workbooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('filter_criteria', sa.JSON(), nullable=True),
    sa.Column('columns_config', sa.JSON(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('completed_rows', sa.Integer(), nullable=True),
    sa.Column('sync_to_leads', sa.Boolean(), nullable=True),
    sa.Column('budget_max_usd', sa.Float(), nullable=True),
    sa.Column('budget_spent_usd', sa.Float(), nullable=True),
    sa.Column('refresh_policy', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbooks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('entity_blocking_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['company_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_blocking_keys', schema=None) as batch_op:
        batch_op.create_index('ix_entity_blocking_key_entity', ['key', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_blocking_keys_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_blocking_keys_key'), ['key'], unique=False)

    op.create_table('person_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company_entity_id', sa.String(), nullable=True),
    sa.Column('identity_keys', sa.JSON(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['company_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_entities_company_entity_id'), ['company_entity_id'], unique=False)

    op.create_table('workbook_enrichments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workbook_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cell_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workbook_id', 'lead_id', 'column_id', name='uq_enrichment_cell')
    )
    with op.batch_alter_table('workbook_enrichments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbook_enrichments_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbook_enrichments_workbook_id'), ['workbook_id'], unique=False)

    op.create_table('workbook_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workbook_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('enrichments', sa.JSON(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('canonical_entity_id', sa.String(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbook_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workbook_rows_canonical_entity_id'), ['canonical_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbook_rows_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workbook_rows_workbook_id'), ['workbook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbook_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbook_rows_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_workbook_rows_lead_id'))
        batch_op.drop_index(batch_op.f('ix_workbook_rows_canonical_entity_id'))

    op.drop_table('workbook_rows')
    with op.batch_alter_table('workbook_enrichments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbook_enrichments_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_workbook_enrichments_lead_id'))

    op.drop_table('workbook_enrichments')
    with op.batch_alter_table('person_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_entities_company_entity_id'))

    op.drop_table('person_entities')
    with op.batch_alter_table('entity_blocking_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_blocking_keys_key'))
        batch_op.drop_index(batch_op.f('ix_entity_blocking_keys_entity_id'))
        batch_op.drop_index('ix_entity_blocking_key_entity')

    op.drop_table('entity_blocking_keys')
    with op.batch_alter_table('workbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbooks_workspace_id'))

    op.drop_table('workbooks')
    with op.batch_alter_table('workbook_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workbook_activity_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_workbook_activity_created_at'))

    op.drop_table('workbook_activity')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('scrape_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_history_url'))
        batch_op.drop_index(batch_op.f('ix_scrape_history_id'))

    op.drop_table('scrape_history')
    with op.batch_alter_table('provider_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_stats_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_stats_field'))

    op.drop_table('provider_stats')
    with op.batch_alter_table('person_intel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_intel_username'))
        batch_op.drop_index(batch_op.f('ix_person_intel_linkedin_url'))
        batch_op.drop_index(batch_op.f('ix_person_intel_id'))

    op.drop_table('person_intel')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_url'))
        batch_op.drop_index(batch_op.f('ix_links_id'))

    op.drop_table('links')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_type'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('entity_review_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_review_pairs_status'))
        batch_op.drop_index(batch_op.f('ix_entity_review_pairs_entity_id'))

    op.drop_table('entity_review_pairs')
    with op.batch_alter_table('entity_merge_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_merge_log_merged_id'))
        batch_op.drop_index(batch_op.f('ix_entity_merge_log_kept_id'))

    op.drop_table('entity_merge_log')
    with op.batch_alter_table('email_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_data_id'))

    op.drop_table('email_data')
    with op.batch_alter_table('company_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_entities_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_company_entities_primary_domain'))
        batch_op.drop_index(batch_op.f('ix_company_entities_corroboration_count'))

    op.drop_table('company_entities')
    with op.batch_alter_table('cell_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cell_traces_workbook_id'))
        batch_op.drop_index(batch_op.f('ix_cell_traces_lead_id'))

    op.drop_table('cell_traces')
    # ### end Alembic commands ###
