"""add provider accuracy columns to provider_stats

Revision ID: f3b30195d51a
Revises: db9a4b81b1e6
Create Date: 2026-06-25 03:59:13.606430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b30195d51a'
down_revision: Union[str, Sequence[str], None] = 'db9a4b81b1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accuracy_samples', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accuracy_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_stats', schema=None) as batch_op:
        batch_op.drop_column('accuracy_updated_at')
        batch_op.drop_column('accuracy_samples')
        batch_op.drop_column('accuracy_score')

    # ### end Alembic commands ###
