"""jobs: worker claim columns

Adds `jobs.locked_at` — the timestamp a worker atomically claimed a job (set
alongside the existing `worker_id`, which was already in the baseline schema).
Together they support horizontally-scalable claiming via FOR UPDATE SKIP LOCKED
and let the heartbeat reaper recover jobs whose worker died mid-flight.

Revision ID: f7274d0aacd9
Revises: 3fa508f4ae76
Create Date: 2026-06-25 04:17:06.155187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7274d0aacd9'
down_revision: Union[str, Sequence[str], None] = '3fa508f4ae76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('locked_at')

    # ### end Alembic commands ###
