[CmdletBinding()]
param(
    [string]$InstallDir = (Join-Path (Get-Location) "opengtm"),
    [switch]$NoStart
)

$ErrorActionPreference = "Stop"
$repositoryUrl = if ($env:OPENGTM_REPOSITORY_URL) {
    $env:OPENGTM_REPOSITORY_URL
} else {
    "https://github.com/debpalash/opengtm.git"
}
if ($env:OPENGTM_INSTALL_DIR) { $InstallDir = $env:OPENGTM_INSTALL_DIR }

function Require-Command([string]$Name, [string]$Message) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) { throw $Message }
}

function New-RandomHex([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
}

Require-Command git "Git is required: https://git-scm.com/downloads"
Require-Command docker "Docker Desktop is required: https://docs.docker.com/desktop/"
& docker compose version *> $null
if ($LASTEXITCODE -ne 0) { throw "Docker Compose v2 is required" }

$candidateRoot = if ($PSScriptRoot) {
    [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
} else { "" }
if ($candidateRoot -and (Test-Path (Join-Path $candidateRoot "docker-compose.yml"))) {
    $installRoot = $candidateRoot
} elseif (Test-Path (Join-Path (Get-Location) "docker-compose.yml")) {
    $installRoot = (Get-Location).Path
} elseif (
    (Test-Path (Join-Path $InstallDir "docker-compose.yml")) -and
    (Test-Path (Join-Path $InstallDir ".env.example"))
) {
    $installRoot = [System.IO.Path]::GetFullPath($InstallDir)
} elseif (Test-Path -LiteralPath $InstallDir) {
    throw "Install path already exists and is not an OpenGTM checkout: $InstallDir"
} else {
    & git clone --depth 1 $repositoryUrl $InstallDir
    if ($LASTEXITCODE -ne 0) { throw "Unable to clone OpenGTM" }
    $installRoot = [System.IO.Path]::GetFullPath($InstallDir)
}

$dataPath = Join-Path $installRoot "data"
if (-not (Test-Path -LiteralPath $dataPath)) {
    New-Item -ItemType Directory -Path $dataPath | Out-Null
}

$envPath = Join-Path $installRoot ".env"
if (-not (Test-Path -LiteralPath $envPath)) {
    Copy-Item -LiteralPath (Join-Path $installRoot ".env.example") -Destination $envPath
    $postgresPassword = New-RandomHex 24
    $runtimePassword = New-RandomHex 24
    $adminPassword = New-RandomHex 12
    $secretKey = New-RandomHex 48
    @"

# Generated by scripts/install.ps1
APP_ENV=local
SECRET_KEY=$secretKey
POSTGRES_USER=yupcha
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=yupcha
DATABASE_URL=postgresql+psycopg://yupcha:$postgresPassword@postgres:5432/yupcha
YUPCHA_RUNTIME_DB_USER=yupcha_runtime
YUPCHA_RUNTIME_DB_PASSWORD=$runtimePassword
APP_DATABASE_URL=postgresql+psycopg://yupcha_runtime:$runtimePassword@postgres:5432/yupcha
SEED_ADMIN_USERNAME=admin
SEED_ADMIN_PASSWORD=$adminPassword
"@ | Add-Content -LiteralPath $envPath -Encoding utf8
    $credentialsPath = Join-Path $installRoot ".opengtm-initial-credentials"
    "URL=http://localhost:3000`nUSERNAME=admin`nPASSWORD=$adminPassword" |
        Set-Content -LiteralPath $credentialsPath -Encoding utf8
    Write-Host "Created .env and one-time credentials at $credentialsPath"
} else {
    Write-Host "Keeping existing $envPath"
}

if (-not $NoStart) {
    Push-Location $installRoot
    try {
        & docker compose up -d --build
        if ($LASTEXITCODE -ne 0) { throw "Docker Compose failed to start" }
        & docker compose ps
    } finally { Pop-Location }
    Write-Host "OpenGTM is starting at http://localhost:3000"
} else {
    Write-Host "Configured $installRoot; run docker compose up -d --build there."
}
