#!/usr/bin/env bash
set -euo pipefail

REPOSITORY_URL="${OPENGTM_REPOSITORY_URL:-https://github.com/debpalash/opengtm.git}"
INSTALL_DIR="${OPENGTM_INSTALL_DIR:-$PWD/opengtm}"
START_STACK=1

usage() {
  cat <<'EOF'
Install OpenGTM with Docker Compose.

Usage: install.sh [--dir PATH] [--no-start]

Environment:
  OPENGTM_REPOSITORY_URL  Git repository to clone
  OPENGTM_INSTALL_DIR     Install directory (default: ./opengtm)
EOF
}

while (($#)); do
  case "$1" in
    --dir) INSTALL_DIR="${2:?--dir requires a path}"; shift 2 ;;
    --no-start) START_STACK=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

command -v git >/dev/null || { echo "git is required" >&2; exit 1; }
command -v docker >/dev/null || { echo "Docker is required: https://docs.docker.com/get-docker/" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "Docker Compose v2 is required" >&2; exit 1; }

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || true)"
candidate_root="$(cd -- "$script_dir/.." 2>/dev/null && pwd || true)"
if [[ -f "$candidate_root/docker-compose.yml" && -f "$candidate_root/.env.example" ]]; then
  install_root="$candidate_root"
elif [[ -f "$PWD/docker-compose.yml" && -f "$PWD/.env.example" ]]; then
  install_root="$PWD"
elif [[ -f "$INSTALL_DIR/docker-compose.yml" && -f "$INSTALL_DIR/.env.example" ]]; then
  install_root="$(cd -- "$INSTALL_DIR" && pwd)"
elif [[ -e "$INSTALL_DIR" ]]; then
  echo "Install path already exists and is not an OpenGTM checkout: $INSTALL_DIR" >&2
  exit 1
else
  git clone --depth 1 "$REPOSITORY_URL" "$INSTALL_DIR"
  install_root="$(cd -- "$INSTALL_DIR" && pwd)"
fi

random_hex() {
  if command -v openssl >/dev/null; then
    openssl rand -hex "$1"
  else
    LC_ALL=C od -An -N "$1" -tx1 /dev/urandom | tr -d ' \n'
  fi
}

cd "$install_root"
if [[ ! -d data ]]; then
  mkdir data
  # Containers use UID 1000 when installed by root; keep the bind mount writable.
  if ((EUID == 0)); then chown 1000:1000 data; fi
fi

if [[ ! -f .env ]]; then
  umask 077
  postgres_password="$(random_hex 24)"
  runtime_password="$(random_hex 24)"
  admin_password="$(random_hex 12)"
  secret_key="$(random_hex 48)"
  app_uid="$(id -u)"
  app_gid="$(id -g)"
  if ((app_uid == 0)); then app_uid=1000; app_gid=1000; fi
  cp .env.example .env
  {
    printf '\n# Generated by scripts/install.sh\n'
    printf 'APP_ENV=local\n'
    printf 'SECRET_KEY=%s\n' "$secret_key"
    printf 'POSTGRES_USER=yupcha\nPOSTGRES_PASSWORD=%s\nPOSTGRES_DB=yupcha\n' "$postgres_password"
    printf 'DATABASE_URL=postgresql+psycopg://yupcha:%s@postgres:5432/yupcha\n' "$postgres_password"
    printf 'YUPCHA_RUNTIME_DB_USER=yupcha_runtime\nYUPCHA_RUNTIME_DB_PASSWORD=%s\n' "$runtime_password"
    printf 'APP_DATABASE_URL=postgresql+psycopg://yupcha_runtime:%s@postgres:5432/yupcha\n' "$runtime_password"
    printf 'SEED_ADMIN_USERNAME=admin\nSEED_ADMIN_PASSWORD=%s\n' "$admin_password"
    printf 'APP_UID=%s\nAPP_GID=%s\n' "$app_uid" "$app_gid"
  } >> .env
  credentials_file="$install_root/.opengtm-initial-credentials"
  printf 'URL=http://localhost:3000\nUSERNAME=admin\nPASSWORD=%s\n' "$admin_password" > "$credentials_file"
  echo "Created .env and one-time credentials at $credentials_file"
else
  echo "Keeping existing $install_root/.env"
fi

if ((START_STACK)); then
  docker compose up -d --build
  docker compose ps
  echo "OpenGTM is starting at http://localhost:3000"
else
  echo "Configured $install_root; run: cd '$install_root' && docker compose up -d --build"
fi
